var scriptData=scriptData||{navbarHeight:90,navbarScrolled:70,navbarScrolledPoint:200,scrollFinishedMessage:"No more items to load.",hoverMenu:{hoverActive:!1,hoverDelay:1,hoverFadeDelay:200}};
jQuery(document).ready(function(b){function r(a){var d=b(a).closest("div.isotope");a=b(a);var c="false"===a.attr("data-flex-slideshow")?!1:!0,e=a.attr("data-flex-animation")?a.attr("data-flex-animation"):"slide",f=a.attr("data-flex-speed")?a.attr("data-flex-speed"):7E3,g=a.attr("data-flex-sliderdirection")?a.attr("data-flex-sliderdirection"):"horizontal",h=a.attr("data-flex-duration")?a.attr("data-flex-duration"):600,k="hide"===a.attr("data-flex-directions")?!1:!0,l="fancy"===a.attr("data-flex-directions-type")?
"flex-directions-fancy":"",m="outside"===a.attr("data-flex-directions-position")?"flex-directions-outside":"",n="thumbnails"===a.attr("data-flex-controls")?"thumbnails":"hide"===a.attr("data-flex-controls")?!1:!0,p="inside"===a.attr("data-flex-controlsposition")?"flex-controls-inside":"flex-controls-outside",q=a.attr("data-flex-controlsalign")?"flex-controls-"+a.attr("data-flex-controlsalign"):"flex-controls-center",r=a.attr("data-flex-itemwidth")?parseInt(a.attr("data-flex-itemwidth"),10):0,s=a.attr("data-flex-itemmax")?
parseInt(a.attr("data-flex-itemmax"),0):0,t=a.attr("data-flex-itemmin")?parseInt(a.attr("data-flex-itemmin"),0):0,u="top"===a.attr("data-flex-captionvertical")?"flex-caption-top":"",v="alternate"===a.attr("data-flex-captionhorizontal")?"flex-caption-alternate":"flex-caption-"+a.attr("data-flex-captionhorizontal");a.addClass(p).addClass(q).addClass(l).addClass(m).addClass(v).addClass(u);a.flexslider({slideshow:c,animation:e,direction:g,slideshowSpeed:parseInt(f),animationSpeed:parseInt(h),itemWidth:r,
minItems:t,maxItems:s,controlNav:n,directionNav:k,prevText:"",nextText:"",smoothHeight:!0,useCSS:!1,after:function(a){0<d.length&&d.isotope("reLayout")}})}function s(){b(".carousel").find(".active .flexslider[id]").each(function(){b(this).hasClass("triggered")||(b(this).addClass("triggered"),r(this))})}function t(a,b,c){b="up"===b?-(a.height()/2):0;var e=parseInt(scriptData.navbarHeight);c.length&&c.hasClass("navbar-sticky")&&c.hasClass("navbar-scrolled")&&(e=parseInt(scriptData.navbarScrolled));
a=a.offset().top;var f=c.length?c.position().top:0;c.length&&c.hasClass("navbar-sticky")&&f+e<=a&&(b+=e);return b}function u(a,b,c){a.length&&b.parent().removeClass("active current-menu-item").end().filter('[href$="'+c.id+'"]').parent().addClass("active current-menu-item")}/Android|iPhone|iPad|iPod|BlackBerry|Windows Phone/i.test(navigator.userAgent||navigator.vendor||window.opera)?b(".section-fullheight").removeClass("section-fullheight").css("min-height",b(window).height()):skrollr.init({forceHeight:!1});
b(".flexslider[id]").filter(function(){return 1>b(this).parents(".carousel").length}).each(function(){var a=this;b(this).imagesLoaded().done(function(b){r(a)})});!navigator.userAgent.match(/iPhone/i)&&!navigator.userAgent.match(/iPod/i)||navigator.userAgent.match(/(iPad|iPhone);.*CPU.*OS 7_\d/i)||window.addEventListener&&window.addEventListener("load",function(){setTimeout(function(){window.scrollTo(0,1)},0)});b('[data-toggle="tooltip"]').tooltip();b(".carousel").carousel({interval:7E3});b(".carousel").on("slid",
function(a){setTimeout(function(){s()},0)});s();b(".chart").each(function(){var a=b(this);a.waypoint(function(){var a=b(this);a.easyPieChart({barColor:a.attr("data-bar-color"),trackColor:a.attr("data-track-color"),lineWidth:a.attr("data-line-width"),scaleColor:!1,animate:1E3,size:a.attr("data-size"),lineCap:"square"})},{triggerOnce:!0,offset:"bottom-in-view"});a.css("left","50%");a.css("margin-left",-a.attr("data-size")/2)});b(".counter").each(function(){var a=b(this);a.waypoint(function(){a.find(".odometer").html(a.attr("data-count"))},
{triggerOnce:!0,offset:"bottom-in-view"})});b("[data-animation]").each(function(){var a=b(this);a.on("mouseenter",function(){a.addClass("animated "+a.attr("data-animation"))});a.on("webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend",function(b){a.removeClass("animated "+a.attr("data-animation"))})});b(".isotope").each(function(a,d){var c=b(d);c.imagesLoaded().done(function(a){setTimeout(function(){c.isotope();setTimeout(function(){c.removeClass("no-transition")},500)},100)})});
b(".isotope-filters").on("click","a",function(a){a=b(this);a.data("filter");var d=a.closest(".isotope-filters");if(a.hasClass("selected"))return!1;d.find("a").removeClass("active");a.addClass("active");d.next().find(".isotope").addBack(".isotope").isotope({filter:a.attr("data-filter")});return!1});b(window).smartresize(function(){b(".isotope").isotope("reLayout")});b(".magnific").magnificPopup({type:"image",removalDelay:300,mainClass:"mfp-fade"});b(".magnific-youtube, .magnific-vimeo, .magnific-gmaps").magnificPopup({disableOn:700,
type:"iframe",mainClass:"mfp-fade",removalDelay:300,preloader:!1,fixedContentPos:!1});b(".magnific-gallery").each(function(a,d){for(var c=b(this),e=b(this).data("links").split(","),f=[],g=0;g<e.length;g++)f.push({src:e[g],title:""});c.magnificPopup({mainClass:"mfp-fade",items:f,gallery:{enabled:!0,tPrev:b(this).data("prev-text"),tNext:b(this).data("next-text")},type:"image"})});b(".magnific-audio").each(function(a,d){var c=b(this),e=b(this).attr("href");c.magnificPopup({items:{src:'<audio controls="" preload="auto"><source src="'+
e+'"></audio>',type:"inline"},callbacks:{open:function(){b(this.currItem.inlineElement).audioPlayer()}},closeBtnInside:!0})});b(".product-gallery").magnificPopup({delegate:"li figcaption a",type:"image",mainClass:"mfp-fade",gallery:{enabled:!0,navigateByImgClick:!0}});b("[data-iconcolor]").each(function(){var a=b(this),d=b(a).css("background-color"),c=b(a).find("i").css("color");a.on("mouseenter",function(){a.css("background-color",a.attr("data-iconcolor"));a.find("i").css("color","#ffffff");a.parents(".social-icons").hasClass("social-simple")&&
a.find("i").css("color",a.attr("data-iconcolor"))});a.on("mouseleave",function(){a.css("background-color",d);a.find("i").css("color",c);a.parents(".social-icons").hasClass("social-simple")&&a.find("i").css("color",c)})});for(var f=document.getElementsByTagName("iframe"),g=0;g<f.length;g++)-1===f[g].src.indexOf("?")?f[g].src+="?wmode=opaque":f[g].src+="&wmode=opaque";b(".accordion-body").on("hide",function(){b(this).parent(".accordion-group").find(".accordion-toggle").addClass("collapsed")});b("html.ie8, html.ie9").find("input, textarea").placeholder();
b(".video-wrapper").fitVids();b(".section-background-video, audio").mediaelementplayer({pauseOtherPlayers:!1,success:function(a){var d=b(a).closest("section"),c=d.outerHeight(),e=a.clientHeight;b(a).css("margin-top",c/2-e/2);d.find(".mejs-overlay-loading").css("margin-top",c/2-e/2)}});b("[data-bgcolor]").each(function(){var a=b(this),d=a.attr("data-bgcolor");a.find(".box-inner").css("background-color",d)});b(".countdown").each(function(){var a=b(this),d=a.attr("data-date");a.countdown(d).on("update.countdown",
function(a){b(this).find(".counter-days").html(a.offset.totalDays);b(this).find(".counter-hours").html(a.offset.hours);b(this).find(".counter-minutes").html(a.offset.minutes);b(this).find(".counter-seconds").html(a.offset.seconds)})});b("body.woo-cart-popup").on("click",".mini-cart-overview a ",function(){var a=b(this);b(".mini-cart-underlay").toggleClass("cart-open");a.attr("href","#mini-cart-container");b("#mini-cart-container").toggleClass("active")});b("select").wrap('<div class="select-wrap">');
var k=b("#masthead"),l=b("#masthead").position(),l=void 0===l?0:l.top,n=b(".navbar").find("a"),p=n.map(function(){var a=this.hash;if(a&&b(a).length)return a});if(p.length){var q=[];b("body").find("section").each(function(){this.id&&q.push(this)});q.length&&b.each(q,function(a,d){var c=b(d);c.waypoint({offset:function(){return t(c,"up",k)},handler:function(a){"up"===a&&u(p,n,d)}});c.waypoint({offset:function(){return t(c,"down",k)},handler:function(a){"down"===a&&u(p,n,d)}})})}b(".navbar a, a.scroll-to-id").on("click",
function(a){var d=this.hash,c=scriptData.navbarHeight;if(d&&b(d).length){a.preventDefault();a=b(d).offset().top;var e=parseInt(scriptData.navbarHeight);if(void 0!==k&&k.hasClass("navbar-sticky")&&l+e<=a)var c=parseInt(scriptData.navbarScrolledPoint),e=parseInt(scriptData.navbarHeight),f=parseInt(scriptData.navbarScrolled),c=c<=a?f:e;b.scrollTo(b(d),800,{axis:"y",offset:-c+1})}});b(".portfolio").each(function(){var a=b(this);a.find(".portfolio-item").css("display","block");a.hasClass("portfolio-hex")&&
(a.find("figure").append('<div class="hex-right"></div><div class="hex-left"></div>'),a.find(".more, .link").addClass("hex-alt"));a.hasClass("portfolio-round")&&a.find("img").addClass("img-circle");a.hasClass("portfolio-shadows")&&a.hasClass("portfolio-hex")&&a.find("figure").wrap('<div class="flat-shadow">');a.hasClass("portfolio-shadows")&&a.hasClass("portfolio-round")&&a.find("figure").wrap('<div class="flat-shadow">');a.hasClass("portfolio-shadows")&&a.hasClass("portfolio-rect")&&a.find("figure").wrap('<div class="flat-shadow flat-rect">');
a.hasClass("portfolio-shadows")&&a.hasClass("portfolio-square")&&a.find("figure").wrap('<div class="flat-shadow flat-square">')});b(".box-hex").append('<div class="hex-right"></div><div class="hex-left"></div>');b("#wp-calendar").addClass("table");b(".top-bar, #masthead").find(".widget_search form").wrap('<div class="top-search">');b(".top-search").append('<i class="fa fa-search search-trigger navbar-text"></i>');b("body").on("click",".search-trigger",function(){b(".top-search").toggleClass("active");
b(".search-trigger").toggleClass("fa-minus");b(".top-search").find("form").fadeToggle(150)});b(".navbar-sticky").waypoint("sticky",{stuckClass:"navbar-stuck"});var h=b("#masthead.navbar-sticky");h.length&&h.hasClass("navbar-sticky")&&(f=h.position().top,b("body").waypoint({offset:-(parseInt(scriptData.navbarScrolledPoint)+f),handler:function(a){h.toggleClass("navbar-scrolled");h.one("MSTransitionEnd webkitTransitionEnd oTransitionEnd transitionend",function(){h.hasClass("refreshing")||b.waypoints("refresh");
h.toggleClass("refreshing")})}}));b("body").waypoint({offset:-200,handler:function(a){"down"===a?b(".go-top").css("bottom","12px").css("opacity","1"):b(".go-top").css("bottom","-44px").css("opacity","0")}});b(".go-top").click(function(a){a.preventDefault();b("html, body").animate({scrollTop:0},300)});b(".os-animation").each(function(){var a=b(this),d=a.attr("data-os-animation"),c=a.attr("data-os-animation-delay");a.css("-webkit-animation-delay",c);a.css("-moz-animation-delay",c);a.css("animation-delay",
c);a.waypoint(function(){b(this).addClass("animated").addClass(d)},{triggerOnce:!0,offset:"80%"})});var m=b("div.isotope-infinite");0<m.length&&m.infinitescroll({navSelector:"div.infinite-scroll",nextSelector:"div.infinite-scroll a",itemSelector:".infinite-item",loading:{finishedMsg:scriptData.scrollFinishedMessage}},function(a){b(a).each(function(a,c){b(c).find("article").hasClass("format-video")&&b(c).find(".video-wrapper").fitVids();b(c).find("article").hasClass("format-audio")&&b(c).find("audio").mediaelementplayer();
if(b(c).hasClass("portfolio-item")){var e=b(c).closest(".portfolio");b(c).css("display","block");b(e).hasClass("portfolio-hex")&&(b(c).find("figure").append('<div class="hex-right"></div><div class="hex-left"></div>'),b(c).find(".more, .link").addClass("hex-alt"));b(e).hasClass("portfolio-round")&&b(c).find("img").addClass("img-circle");b(e).hasClass("portfolio-shadows")&&b(e).hasClass("portfolio-hex")&&b(c).find("figure").wrap('<div class="flat-shadow">');b(e).hasClass("portfolio-shadows")&&b(e).hasClass("portfolio-round")&&
b(c).find("figure").wrap('<div class="flat-shadow">');b(e).hasClass("portfolio-shadows")&&b(e).hasClass("portfolio-rect")&&b(c).find("figure").wrap('<div class="flat-shadow flat-rect">');b(e).hasClass("portfolio-shadows")&&b(e).hasClass("portfolio-square")&&b(c).find("figure").wrap('<div class="flat-shadow flat-square">')}});m.isotope("appended",b(a),function(){m.isotope("reLayout")})});!0===scriptData.hoverMenu.hoverActive&&b(".navbar .dropdown").hover(function(){b(this).find(".dropdown-menu").first().stop(!0,
!0).delay(scriptData.hoverMenu.hoverDelay).fadeIn(parseInt(scriptData.hoverMenu.hoverFadeDelay))},function(){b(this).find(".dropdown-menu").first().stop(!0,!0).delay(scriptData.hoverMenu.hoverDelay).fadeOut(parseInt(scriptData.hoverMenu.hoverFadeDelay))})});
